Aastha/Controllers/RoleController.cs
using System.Linq;
using System.Threading.Tasks;
using Aastha.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Aastha.Controllers
{
    [Authorize]
    public class RoleController: Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(){
            var roles = await _roleManager.Roles.Select(s => new RoleViewModel{
                Id = s.Id,
                Name = s.Name
            }).ToListAsync();
            return View(roles);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };

            return View(model);
        }

        public IActionResult Create(){
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreatePost(RoleViewModel model)
        {
            if (model==null)
            {
                return NotFound();
            }
            if (await _roleManager.RoleExistsAsync(model.Name))
            {
                ModelState.AddModelError("", "Name is exist");
                
            }
            var role = new IdentityRole()
            {
                Name = model.Name
            };

            await _roleManager.CreateAsync(role);
            TempData["Success"] = "The data has been added...!";
            return RedirectToAction("Index");
        }

         public async Task<IActionResult> Edit(string id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }


        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(RoleViewModel model)
        {
            if (model==null)
            {
                return NotFound();
            }

            if (await  _roleManager.RoleExistsAsync(model.Name))
            {
                ModelState.AddModelError("","Name is exist");
            }

            var role = await _roleManager.FindByIdAsync(model.Id);
            role.Name = model.Name;
            role.NormalizedName = model.Name.ToUpper();
            await _roleManager.UpdateAsync(role);
            TempData["Success"] = "The data has been updated...!";
            return RedirectToAction("Index");
        }

        //public async Task<IActionResult> Delete(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var role = await _roleManager.FindByIdAsync(id);
        //    var model = new RoleViewModel()
        //    {
        //        Id = role.Id,
        //        Name = role.Name
        //    };
        //    return View(model);
        //}


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(role);
            TempData["Success"] = "The data has been deleted...!";
            return RedirectToAction("Index");
        }
    }
}

Aastha/Controllers/UserController.cs
using System.Linq;
using System.Threading.Tasks;
using Aastha.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Aastha.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.Select(s => new UserViewModel
            {
                Id = s.Id,
                Email = s.Email
            }).ToListAsync();
            return View(users);
        }

        public async Task<IActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _roleManager.Roles.ToListAsync();
            var userRoles = (await _userManager.GetRolesAsync(user)).ToList();  // admin ==> Super Admin, Admin and user || user ==>user

            var model = new UserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                UserInRoles = roles.Select(s=>new RoleViewModel()
                {
                    Id = s.Id,
                    Name = s.Name,
                    Select = userRoles.Exists(x=>x==s.Name)
                }).ToList()
            };

            return View(model);
        }

        [Authorize(Policy = "OnlyAdmin")]
        [HttpPost,ActionName("Details")]
        public async Task<IActionResult> Update(string id, UserViewModel model)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == id);
            var roles = await _roleManager.Roles.ToListAsync();

            foreach (var role in model.UserInRoles)
            {

                if (role.Select)
                {
                    await _userManager.AddToRoleAsync(user, roles.FirstOrDefault(x => x.Id == role.Id)?.Name);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, roles.FirstOrDefault(x => x.Id == role.Id)?.Name);
                }
            }

            return RedirectToAction("Index");
        }

        //[HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
    }
}

Aastha/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<html lang="en">
<head>

    <title>Ashtha</title>

  

    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="icon" href="~/css/images/Aastha.jpg">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    @*  <link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
    <script src="~/lib/bootstrap/js/delete.js" asp-append-version="true"></script>

    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />


</head>
<body>
    @*Header*@
    <div class="container">
        <div class="row">
            <div class=" col-md-3 col-xs-4">
                <a href="#">
                    <img class="img-responsive" src="~/css/images/Aastha.jpg" />
                </a>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="site">

                    <p class="site-title"><a href="#" rel="home">Aastha Coaching Classes</a></p>

                    <p class="site-description">Best Coaching Classes in Ulhasnagar</p>
                </div>
            </div>



            <div style="float:right">
                <div class="a2a_kit a2a_kit_size_32 a2a_default_style" data-a2a-url="http://aastha.aakaarinfotech.com/Forms/frmRegister.aspx" data-a2a-title="Aastha Classes">
                    <a class="a2a_dd" href="https://www.addtoany.com/share"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
                </div>
                <script>
                    var a2a_config = a2a_config || {};
                    a2a_config.onclick = 1;
                </script>
                <script async src="https://static.addtoany.com/menu/page.js"></script>
            </div>

        </div>
    </div>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    @if (SignInManager.IsSignedIn(User))
                    {
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Role" asp-action="Index">Roles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
            </li>
            @*<li class="nav-item ">
                    <i class="nav-link">
                        @User.Identity.Name
                    </i>
                </li>
                <li class="nav-item active">
                    <form class="nav-link" asp-controller="Account" asp-action="Logout">
                        <input type="submit" class="btn btn-sm btn-danger" value="Logout" />
                    </form>
                </li>*@
        </ul>
                        <span class="navbar-text">
                            <ul class="navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="~/css/images/user.png" width="20" class="img-circle" alt="Avatar"> <span>Hello @UserManager.GetUserName(User)!</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                                    <ul class="dropdown-menu">
                                        @*<li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
                                            <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                                            <li><a href="#"><i class="lnr lnr-cog"></i> <span>Reset Password</span></a></li>*@
                                        <li>
                                            <form asp-area="" asp-controller="Account" asp-action="LogOut" id="logoutForm"
                                                  method="post" asp-route-returnUrl="@Url.Action("Login", "Account")">
                                                <a class="btn btn-link text-dark" href="javascript:document.getElementById('logoutForm').submit()"><i class="lnr lnr-cog"></i> <span>LogOut</span></a>
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            </ul>

                        </span>}
                </div>
            </div>
        </nav>

    </header>

    @*End Header*@
    @*<div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@
    <div class="container body-content">
        <div class="container body-content" style="margin-top:10px;">
            @if (TempData["Success"] != null)
            {
<div class="alert alert-success col-md-3 col-lg-3 col-sm-2 col-2 text-center" style="position:fixed; right:10px">
    @TempData["Success"]
</div>}
            @if (TempData["Error"] != null)
            {
<div class="alert alert-danger col-md-3 col-lg-3 col-sm-2 col-2 text-center" style="position:sticky; right:10px">
    @TempData["Error"]

</div>}


            @RenderBody()
            @*<hr />*@
            @*<footer>
                    <p>&copy; 2021 - DataBase_Firstapproaches</p>
                </footer>*@
        </div>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Aastha - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <scripts src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></scripts>
    <script src="~/lib/bootstrap/js/delete.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>